ROOT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_main.urls')),
    path('accounts/', include('app_users.urls')),

    # Social oauth
    path('social-auth/', include('social_django.urls', namespace='social')),

    # Forget password
    path('password-reset/', PasswordResetView.as_view(template_name='password-reset/password-reset.html'),
         name='password_reset'),
    path(
        'password-reset/done/',PasswordResetDoneView.as_view(template_name='password-reset/password-reset-done.html'),
        name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password-reset/password-reset-confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='password-reset/password-reset-complete.html'), name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.DevelopersView.as_view(), name='developers'),
    path('project-create/', views.ProjectCreate.as_view(), name='create_project'),
    path('project/<int:project_id>', views.ProjectDetail.as_view(), name='detail_project'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile'),
    path('projects/', views.projects_view, name='projects'),
    path('send-message/<int:receiver_id>', views.handle_message_submission, name='send_message'),

]

app_main/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Project(models.Model):
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='project-photos/',
                              default='project-photos/project-default.jpg',null=True, blank=True)
    tags = models.ManyToManyField(to='Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    source_link = models.URLField(null=True, blank=True)
    demo_link = models.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name} _ {self.owner.fullname}'

class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Message(models.Model):
    sender = models.ForeignKey(to=User, related_name='sent_message', on_delete=models.SET_NULL, null=True)
    receiver = models.ForeignKey(to=User, related_name='receiver_message', on_delete=models.CASCADE)
    fullname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.sender} - {self.receiver} - {self.body[:50]}'

class Comment(models.Model):
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)
    project = models.ForeignKey(to=Project,related_name='comments', on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.owner.fullname} - {self.body[:50]}'

app_main/forms.py
from django.forms import ModelForm

from .models import Project, Message

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'image', 'source_link', 'demo_link']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'input input--text',
            })

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['fullname', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({'class': 'input input--text'})
        if user and user.is_authenticated:
            self.fields['fullname'].required = False
            self.fields['email'].required = False

app_main/views.py
from django.views.generic import ListView, CreateView, DetailView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from .forms import ProjectForm, MessageForm
from .models import Project, Tag, Comment

User = get_user_model()


class DevelopersView(ListView):
    template_name = 'app_main/developers.html'
    paginator_class = Paginator
    paginate_by = 3

    def get_queryset(self):
        return User.objects.all()

    context_object_name = 'developers'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        page_obj = context['page_obj']
        left_index = page_obj.number - 1
        right_index = page_obj.number + 1

        if left_index < 1:
            left_index = 1

        if right_index > page_obj.paginator.num_pages:
            right_index = page_obj.paginator.num_pages

        custom_range = range(left_index, right_index + 1)
        context['custom_range'] = custom_range
        return context


class ProjectCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("login")
    model = Project
    template_name = 'app_main/project_form.html'
    form_class = ProjectForm
    extra_context = {
        'btn_text': 'Create project'
    }

    def get_success_url(self):
        return reverse('account', kwargs={'user_id': self.request.user.id})

    def form_valid(self, form):
        tags = self.request.POST.get('tags', '').split(',')
        project = form.save(commit=False)
        project.owner = self.request.user
        project.save()

        for tag_name in tags:
            tag_name = tag_name.strip().lower()
            tag, created = Tag.objects.get_or_create(name=tag_name)
            project.tags.add(tag)

        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class ProjectDetail(DetailView):
    model = Project
    template_name = 'app_main/project.html'
    pk_url_kwarg = 'project_id'

    def post(self, request, *args, **kwargs):
        project = self.get_object()
        comment = request.POST.get('comment')

        if comment and len(comment.strip()) >= 10:
            new_comment = Comment.objects.create(
                owner=request.user,
                project=project,
                body=comment
            )
            new_comment.save()
            return redirect(f'/project/{project.id}#comments-section')

        return self.get(request, *args, **kwargs)


class ProfileView(DetailView):
    model = User
    template_name = 'app_main/profile.html'
    pk_url_kwarg = 'user_id'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['dev_skills'] = self.get_object().skill_set.exclude(description='')
        context['other_skills'] = self.get_object().skill_set.filter(description='')

        return context


def handle_message_submission(request, receiver_id):
    if request.method == 'POST':
        form = MessageForm(request.POST or None, user=request.user)
        if form.is_valid():
            message = form.save(commit=False)

            if request.user.is_authenticated:
                message.sender = request.user
                message.fullname = request.user.fullname
                message.email = request.user.email

            message.receiver = get_object_or_404(User, id=receiver_id)
            message.save()
            return redirect('profile', user_id=receiver_id)

    else:
        form = MessageForm()

    if request.user.is_authenticated:
        form.fields.pop('fullname', None)
        form.fields.pop('email', None)

    context = {
        'form': form,
        'btn_text': 'Send message',
    }

    return render(request, 'form.html', context)


def projects_view(request):
    project_list = Project.objects.all()

    paginator = Paginator(project_list, 3)
    page_number = request.GET.get('page')
    projects = paginator.get_page(page_number)

    context = {
        'projects': projects,
    }
    return render(request, 'app_main/projects.html', context)

app_main/templates/app_main/developers.html
{% extends 'base/base.html' %}

{% block content %}
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                <h2>FROM AROUND THE WORLD</h2>
            </div>

            <div class="hero-section__search">
                <form class="form" action="" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search Developers</label>
                        <input
                            class="input input--text"
                            id="formInput#search"
                            type="text"
                            name="query"
                            placeholder="Search by developer name"
                            value="{{ request.GET.query }}"
                        />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>

    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">
                {% for account in developers %}
                <div class="column card">
                    <div class="dev">
                        <a href="{% url 'profile' account.id %}" class="card__body">
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="{{ account.profile_image.url }}" />
                                <div class="dev__meta">
                                    <h3>{{ account.fullname }}</h3>
                                    <h5>{{ account.occupation }}</h5>
                                </div>
                            </div>
                            <p class="dev__info">{{ account.bio|truncatechars:100|linebreaksbr }}</p>
                        </a>
                    </div>
                </div>
                {% endfor %}
                {% if developers|length == 0 %}
                    <p>No developers found.</p>
                {% endif %}
            </div>
        </div>
    </section>

    <!-- Pagination -->
    <div class="pagination">
        <ul class="container">
            <li>
                <a href="{% if not page_obj.has_previous %} #! {% else %} ?query={{ request.GET.query }}&page={{ page_obj.previous_page_number }} {% endif %}" class="btn {% if not page_obj.has_previous %} btn--disabled {% endif %}">&#10094; Prev</a>
            </li>
            {% for page in custom_range %}
            <li>
                <a href="{% if page == page_obj.number %}#!{% else %} ?query={{ request.GET.query }}&page={{ page }} {% endif %}" class="btn {% if page == page_obj.number %} btn--sub {% endif %}">{{ page }}</a>
            </li>
            {% endfor %}
            <li>
                <a href="{% if not page_obj.has_next %} #! {% else %} ?query={{ request.GET.query }}&page={{ page_obj.next_page_number }} {% endif %}" class="btn {% if not page_obj.has_next %} btn--disabled {% endif %}">Next &#10095;</a>
            </li>
        </ul>
        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
    </div>

</main>
{% endblock content %}

app_main/templates/app_main/profile.html
{% extends 'base/base.html' %}

{% block content %}
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ object.profile_image.url }}" alt="{{ object.fullname }}" />
              <h2 class="dev__name">{{ object.name }}</h2>
              <p class="dev__title">{{ object.occupation }}</p>
              <p class="dev__location">Based in {{ object.location }}</p>
              <ul class="dev__social">
                  {% if account.social_telegram %}
                    <li>
                        <a title="Telegram" href="{{ account.social_telegram }}" target="_blank">
                            <i class="bi bi-telegram"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if object.social_instagram %}
                    <li>
                        <a title="Instagram" href="{{ object.social_instagram }}" target="_blank">
                            <i class="bi bi-instagram"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if object.social_facebook %}
                    <li>
                        <a title="Facebook" href="{{ object.social_facebook }}" target="_blank">
                            <i class="bi bi-facebook"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if object.social_twitter %}
                    <li>
                        <a title="Twitter" href="{{ object.social_twitter }}" target="_blank">
                            <i class="bi bi-twitter"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if object.social_whatsapp %}
                      <li>
                        <a title="WhatsApp" href="{{ object.social_whatsapp }}" target="_blank">
                            <i class="bi bi-whatsapp"></i>
                        </a>
                      </li>
                  {% endif %}

                  {% if object.social_linkedin %}
                    <li>
                        <a title="LinkedIn" href="{{ object.social_linkedin }}" target="_blank">
                            <i class="bi bi-linkedin"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if object.social_youtube %}
                    <li>
                        <a title="YouTube" href="{{ object.social_youtube }}" target="_blank">
                            <i class="bi bi-youtube"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if object.social_github %}
                    <li>
                        <a title="GitHub" href="{{ object.social_github }}" target="_blank">
                            <i class="bi bi-github"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if object.social_website %}
                    <li>
                        <a title="Website" href="{{ object.social_website }}" target="_blank">
                            <i class="bi bi-globe"></i>
                        </a>
                    </li>
                  {% endif %}

              </ul>
                {% if request.user.id != object.id %}
                    <a href="{% url 'send_message' object.id %}" class="btn btn--sub btn--lg">Send Message </a>
                {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
                {{ object.bio|linebreaksbr }}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              {% for skill in dev_skills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{ skill.name }}</h4>
                <p class="devSkill__info">
                  {{ skill.description|linebreaksbr }}
                </p>
              </div>
              {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in other_skills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{ skill.namae }}</small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

            {% for project in object.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'detail_project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{ project.image.url }}" alt="{{ project.name }}" />
                    <div class="card__body">
                      <h3 class="project__title">{{ project.name }}</h3>
                      <p><a class="project__author" href="{% url 'profile' object.id %}">By {{ project.owner.fullname }}</a></p>
                      <div class="project__tags">
                          {% for tag in project.tags.all %}
                            <span class="tag tag--pill tag--main">
                                <small>{{ tag.name }}</small>
                            </span>
                          {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
            {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
</main>
{% endblock content %}

app_main/templates/app_main/project.html
{% extends 'base/base.html' %}

{% block content %}
<main class="singleProject my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <h3 class="singleProject__subtitle">Tools & Stacks</h3>
                <div class="singleProject__toolStack">
                    {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--sub tag--lg">
                            <small>{{ tag.name|upper }}</small>
                        </span>
                    {% endfor %}
                </div>
                {% if object.source_link %}
                    <a class="singleProject__liveLink" href="{{ object.source_link }}" target="_blank">
                        <i class="bi bi-link-45deg"></i>
                        Source Code
                    </a>
                {% endif %}
                {% if object.demo_link %}
                    <a class="singleProject__liveLink" href="{{ object.demo_link }}" target="_blank">
                        <i class="bi bi-globe"></i>
                        Demo Code
                    </a>
                {% endif %}
            </div>
            <div class="column column--2of3">
                <img class="singleProject__preview" src="{{ object.image.url }}" alt="{{ object.name }}" />
                <a href="{% url 'profile' object.owner.id %}" class="singleProject__developer">{{ object.owner.fullname }}</a>
                <h2 class="singleProject__title">{{ object.name }}</h2>
                <h3 class="singleProject__subtitle">About the Project</h3>
                <div class="singleProject__info">
                    {{ object.description|linebreaksbr }}
                </div>

                <div class="comments">
                    <h3 class="singleProject__subtitle">Feedback</h3>

                    <!-- Comments form -->
                    <form class="form" action="{{ request.path }}" method="POST">
                        {% csrf_token %}
                        <!-- Textarea -->
                        <div class="form__field">
                            <label for="formInput#textarea">Comments: </label>
                            <textarea class="input input--textarea" name="comment" id="formInput#textarea"
                                placeholder="Write your comments here📝..."></textarea>
                        </div>
                        <input class="btn btn--sub btn--lg" type="submit" value="Comment" />
                    </form>

                    <!-- Comments List -->
                    <div class="commentList">
                        {% for comment in object.comments.all %}
                            <div class="comment">
                                <a href="{% url 'profile' comment.owner.id %}">
                                    <img class="avatar avatar--md"
                                        src="{{ comment.owner.profile_image.url }}" alt="{{ comment.owner.fullname }}" />
                                </a>
                                <div class="comment__details">
                                    <a href="{% url 'profile' comment.owner.id %}" class="comment__author">{{ comment.owner.fullname }}</a>
                                    <p class="comment__info">
                                        {{ comment.body }}
                                    </p>
                                    <p class="comment__date">{{ comment.created_at|date:"F j, Y, g:i " }}</p>
                                </div>
                            </div>
                        {% empty %}
                            <p>No comments yet. Be the first to comment!</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

app_main/templates/app_main/project_form.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="#" onclick="window.history.back()">
                <i class="bi bi-arrow-left"></i>
            </a>
            <br />

            <form class="form" method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                    {% if field.name == 'description' %}
                        <div class="form__field">
                            <label for="id_{{ field.name }}">{{ field.label }}: </label>
                            {{ field }}
                        </div>
                        <div class="form__field">
                            <div id="tags" style="margin-bottom: 10px;"></div>
                            <input type="hidden" name="tags" id="tags_hidden">
                            <input class="input" type="text" name="custom_tags" id="id_tags">
                        </div>
                    {% else %}
                        <div class="form__field">
                            <label for="id_{{ field.name }}">{{ field.label }}: </label>
                            {{ field }}
                        </div>
                    {% endif %}
                {% endfor %}

                <button class="btn btn--sub btn--lg my-md" type="submit" id="submit-form-btn">{{ btn_text }}</button>
            </form>
        </div>
    </div>
</main>

<script type="text/javascript">
    const tagsInput = document.getElementById('id_tags');
    const tagsHiddenInput = document.getElementById('tags_hidden');
    const tagsContainer = document.getElementById('tags');


    // Helper function to update the hidden input with all current tags
    const updateHiddenInput = () => {
        const tags = Array.from(document.querySelectorAll('.tag-text')).map(tag => tag.textContent.trim());
        tagsHiddenInput.value = tags.join(',');
    };

    // Event handler for adding new tags
    const addTag = (newTag) => {
        const tagElement = document.createElement('span');
        tagElement.className = 'tag tag--pill tag--sub tag--lg';

        const tagText = document.createElement('small');
        tagText.className = 'tag-text';
        tagText.textContent = newTag;
        tagText.style.display = 'flex';
        tagText.style.alignItems = 'center';
        tagText.style.gap = '10px';

        const closeIcon = document.createElement('i');
        closeIcon.className = 'bi bi-x-lg tag-close';
        closeIcon.style.cursor = 'pointer';

        closeIcon.addEventListener('click', () => {
            tagElement.remove();
            updateHiddenInput();
        });

        tagText.appendChild(closeIcon);
        tagElement.appendChild(tagText);
        tagsContainer.appendChild(tagElement);

        updateHiddenInput();
    };

    // Main input listener for handling new tag creation
    tagsInput.addEventListener('keyup', (event) => {
        if (event.key === ',' || event.key === ' ') {
            const newTag = event.target.value.replace(',', '').trim();

            if (newTag && ![...document.querySelectorAll('.tag-text')].some(tag => tag.textContent.trim() === newTag)) {
                addTag(newTag);
            }
            tagsInput.value = '';  // Clear input after adding the tag
        }
    });
</script>
{% endblock content %}

app_main/templates/app_main/projects.html
{% extends 'base/base.html' %}

{% block content %}
<main class="projects">

    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>

    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">
          {% for project in projects %}
          <div class="column">
            <div class="card project" >
              <a href="{% url 'projects' %}" class="project">
                <img class="project__thumbnail" src="{{ project.image.url }}" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{ project.name }}</h3>
                  <p><a class="project__author" href="{% url 'profile' project.owner.id %}">By {{ project.owner.fullname }}</a></p>

                  <div class="project__tags">
                    {% for tag in project.tags.all %}
                    <span class="tag tag--pill tag--main">
                      <small>{{ tag.name }}</small>
                    </span>
                    {% endfor %}
                  </div>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>

    <!-- Pagination -->
    <div class="pagination">
      <ul class="container">
        {% if projects.has_previous %}
          <li><a href="?page={{ projects.previous_page_number }}" class="btn">&#10094; Prev</a></li>
        {% else %}
          <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        {% endif %}

        {% for num in projects.paginator.page_range %}
          {% if projects.number == num %}
            <li><a href="?page={{ num }}" class="btn btn--sub">{{ num|add:"0" }}</a></li>
          {% else %}
            <li><a href="?page={{ num }}" class="btn">{{ num|add:"0" }}</a></li>
          {% endif %}
        {% endfor %}

        {% if projects.has_next %}
          <li><a href="?page={{ projects.next_page_number }}" class="btn">Next &#10095;</a></li>
        {% else %}
          <li><a href="#" class="btn btn--disabled">Next &#10095;</a></li>
        {% endif %}
      </ul>
    </div>
  </main>
{% endblock content %}

app_main/templates/app_main/send_message.html
{% extends 'base/base.html' %}

{% block content %}
 <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="inbox.html"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">Working Opportunity for Web Design Company</h4>
          <a href="profile.html" class="message__author">Dennis Ivanov</a>
          <p class="message__date">May 31, 2021, 04:37 PM</p>
          <div class="message__body">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, ea? Facere minus vel nam, quas nisi dolore
            possimus tempora commodi. Praesentium nisi totam quas pariatur culpa nostrum dolore, nemo voluptatem!
            <br /><br />
            Voluptate dolores veniam ducimus cumque, harum fuga quaerat, culpa distinctio voluptas magnam a unde
            reiciendis similique necessitatibus obcaecati voluptatibus deserunt voluptatum numquam ullam in ipsum, ea
            aperiam. Dolorum rerum pariatur quaerat. Debitis tempora aliquid libero alias aperiam illo fuga ipsum magni
            quia.
          </div>
      </div>
    </div>
 </main>
{% endblock content %}