ROOT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_main.urls')),
    path('accounts/', include('app_users.urls')),

    # Social oauth
    path('social-auth/', include('social_django.urls', namespace='social')),

    # Forget password
    path('password-reset/', PasswordResetView.as_view(template_name='password-reset/password-reset.html'),
         name='password_reset'),
    path(
        'password-reset/done/',PasswordResetDoneView.as_view(template_name='password-reset/password-reset-done.html'),
        name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password-reset/password-reset-confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='password-reset/password-reset-complete.html'), name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views
urlpatterns = [
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('login/', LoginView.as_view(template_name='app_users/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('account/<int:user_id>/', views.AccountView.as_view(), name='account'),
    path('update-account/<int:user_id>/', views.UpdateAccountView.as_view(), name='update_account'),

    path('create-skill/', views.CreateSkillView.as_view(), name='create_skill'),
    path('update-skill/<int:skill_id>/', views.UpdateSkillView.as_view(), name='update_skill'),
    path('delete-skill/<int:skill_id>/', views.DeleteSkillView.as_view(), name='delete_skill'),
    path('update-project/<int:project_id>/', views.UpdateProjectView.as_view(), name='update_project'),
    path('delete-project/<int:project_id>/', views.DeleteProjectView.as_view(), name='delete_project'),
    path('inbox/<int:user_id>/', views.inbox_view, name='inbox'),

]

app_main/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Project(models.Model):
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='project-photos/',
                              default='project-photos/project-default.jpg',null=True, blank=True)
    tags = models.ManyToManyField(to='Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    source_link = models.URLField(null=True, blank=True)
    demo_link = models.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name} _ {self.owner.fullname}'

class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Message(models.Model):
    sender = models.ForeignKey(to=User, related_name='sent_message', on_delete=models.SET_NULL, null=True)
    receiver = models.ForeignKey(to=User, related_name='receiver_message', on_delete=models.CASCADE)
    fullname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.sender} - {self.receiver} - {self.body[:50]}'

class Comment(models.Model):
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)
    project = models.ForeignKey(to=Project,related_name='comments', on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.owner.fullname} - {self.body[:50]}'

app_users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from .managers import MyUserManager as UserManager

class User(AbstractUser):
    first_name = models.CharField(max_length=100, verbose_name="First Name")
    last_name = models.CharField(max_length=100, verbose_name="Last Name")
    username = models.CharField(max_length=100, verbose_name="Username",
                                null=True, blank=True)
    email = models.EmailField(unique=True, verbose_name="Email")
    bio = models.TextField(verbose_name="About", null=True, blank=True)
    profile_image = models.ImageField(upload_to="profile-images/", verbose_name="Profile Image",
                                      default="profile-images/user-default.jpg",
                                      null=True, blank=True)
    location = models.CharField(max_length=200, verbose_name="Basin in", null=True, blank=True)
    occupation = models.CharField(max_length=200, verbose_name="Occupation", null=True, blank=True)
    social_telegram = models.URLField(verbose_name="Telegram", max_length=200, null=True, blank=True)
    social_instagram = models.URLField(verbose_name="Instagram", max_length =200, null=True, blank=True)
    social_facebook = models.URLField(verbose_name="Facebook", max_length =200, null=True, blank=True)
    social_twitter = models.URLField(verbose_name="Twitter", max_length =200, null=True, blank=True)
    social_whatsapp = models.URLField(verbose_name="Whatsapp", max_length =200, null=True, blank=True)
    social_linkedin = models.URLField(verbose_name="LinkedIn", max_length =200, null=True, blank=True)
    social_youtube = models.URLField(verbose_name="YouTube", max_length =200, null=True, blank=True)
    social_github = models.URLField(verbose_name="GitHub", max_length =200, null=True, blank=True)
    social_website = models.URLField(verbose_name="Website", max_length =200, null=True, blank=True)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    @property
    def fullname(self):
        return f"{self.first_name} {self.last_name}"

    def get_fullname(self):
        return f"{self.first_name} {self.last_name}"

    def set_fullname(self, value):
        names = value.split()
        self.first_name, self.last_name = names[0], " ".join(names[1:])

    fullname = property(get_fullname, set_fullname)

class Skill(models.Model):
    owner = models.ForeignKey(to=User,  on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.owner}-{self.name}'

app_users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import ModelForm

from app_users.models import Skill

User = get_user_model()

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email','first_name', 'last_name', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'input input--text',
            })

class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = ['name', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'input input--text',
            })

class UserEditForm(ModelForm):
    class Meta:
        model = User
        exclude = ['password', 'user_permissions', 'last_login', 'is_active', 'is_staff', 'is_superuser', 'groups', 'date_joined']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'input input--text',
            })

app_users/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth import get_user_model, logout
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator

from app_users.forms import UserRegistrationForm, UserEditForm
from app_main.models import Message, Project
from app_users.models import Skill
from app_users.forms import SkillForm
from app_main.forms import ProjectForm

User = get_user_model()

class UserRegistrationView(CreateView):
    model = User
    template_name = 'app_users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('login')

def logout_view(request):
    logout(request)
    return redirect('login')


class AccountView(DetailView):
    model = User
    template_name = 'app_users/account.html'
    pk_url_kwarg = 'user_id'
    context_object_name = 'account'

class CreateSkillView(CreateView):
    model = Skill
    template_name = 'form.html'
    form_class = SkillForm

    def form_valid(self, form):
        skill = form.save(commit=False)
        skill.owner = self.request.user
        skill.save()
        return redirect('account', user_id=self.request.user.id)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['btn_text'] = 'Create skill'
        return context

    def get_success_url(self) ->str:
        return reverse('account', user_id=self.request.user.id)

class UpdateSkillView(UpdateView):
    model = Skill
    template_name = 'form.html'
    form_class = SkillForm
    pk_url_kwarg = 'skill_id'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['btn_text'] = 'Update skill'
        return context

    def get_success_url(self) ->str:
        return reverse('account', kwargs={'user_id':self.request.user.id})

class DeleteSkillView(DeleteView):
    model = Skill
    template_name = 'delete.html'
    pk_url_kwarg = 'skill_id'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['confirmation_text'] = (f'Are you sure to delete "{self.get_object().name}" ?')
        return context

    def get_success_url(self) ->str:
        return reverse('account', kwargs={'user_id':self.request.user.id})

class UpdateAccountView(UpdateView):
    model = User
    template_name = 'form.html'
    form_class = UserEditForm
    pk_url_kwarg = 'user_id'
    success_url = reverse_lazy('account')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['btn_text'] = 'Update account'
        return context

    def get_success_url(self):
        return reverse('account', kwargs={'user_id':self.request.user.id})


def inbox_view(request, user_id):
    user = get_object_or_404(User, id=user_id)
    messages = Message.objects.filter(receiver=user).order_by('is_read', '-created_at')

    unread_messages = Message.objects.filter(receiver=user, is_read=False).order_by('-created_at')
    read_messages = Message.objects.filter(receiver=user, is_read=True).order_by('-created_at')
    messages.filter(is_read=False).update(is_read=True)


    context = {
        'user': user,
        'messages': messages,
        'unread_messages': unread_messages,
        'read_messages': read_messages,
    }

    return render(request, 'app_users/inbox.html', context)

class UpdateProjectView(UpdateView):
    model = Project
    template_name = 'form.html'
    form_class = ProjectForm
    pk_url_kwarg = 'project_id'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['btn_text'] = 'Update project'
        return context

    def get_success_url(self) ->str:
        return reverse('account', kwargs={'user_id':self.request.user.id})

class DeleteProjectView(DeleteView):
    model = Project
    template_name = 'delete.html'
    pk_url_kwarg = 'project_id'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['confirmation_text'] = (f'Are you sure to delete "{self.get_object().name}" ?')
        return context

    def get_success_url(self) ->str:
        return reverse('account', kwargs={'user_id':self.request.user.id})

app_users/templates/app_users/account.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update_account' user_id=request.user.id %}"><i class="im im-edit"></i>Edit</a>
              <img class="avatar avatar--xl dev__avatar"
                   src="{{ account.profile_image.url }}"
                />
              <h2 class="dev__name">{{ account.fullname }}</h2>
              <p class="dev__title">
                  {% if account.occupation %}
                    {{ account.occupation }}
                  {% else %}
                      No occupation
                  {% endif %}
              </p>
              <p class="dev__location">
                  {% if account.location %}
                    {{ account.location }}
                  {% else %}
                      No location
                  {% endif %}
              </p>
              <ul class="dev__social">
                  {% if account.social_telegram %}
                    <li>
                        <a title="Telegram" href="{{ account.social_telegram }}" target="_blank">
                            <i class="bi bi-telegram"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if account.social_instagram %}
                    <li>
                        <a title="Instagram" href="{{ account.social_instagram }}" target="_blank">
                            <i class="bi bi-instagram"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if account.social_facebook %}
                    <li>
                        <a title="Facebook" href="{{ account.social_facebook }}" target="_blank">
                            <i class="bi bi-facebook"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if account.social_twitter %}
                    <li>
                        <a title="Twitter" href="{{ account.social_twitter }}" target="_blank">
                            <i class="bi bi-twitter"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if account.social_whatsapp %}
                      <li>
                        <a title="WhatsApp" href="{{ account.social_whatsapp }}" target="_blank">
                            <i class="bi bi-whatsapp"></i>
                        </a>
                      </li>
                  {% endif %}

                  {% if account.social_linkedin %}
                    <li>
                        <a title="LinkedIn" href="{{ account.social_linkedin }}" target="_blank">
                            <i class="bi bi-linkedin"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if account.social_youtube %}
                    <li>
                        <a title="YouTube" href="{{ account.social_youtube }}" target="_blank">
                            <i class="bi bi-youtube"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if account.social_github %}
                    <li>
                        <a title="GitHub" href="{{ account.social_github }}" target="_blank">
                            <i class="bi bi-github"></i>
                        </a>
                    </li>
                  {% endif %}

                  {% if account.social_website %}
                    <li>
                        <a title="Website" href="{{ account.social_website }}" target="_blank">
                            <i class="bi bi-globe"></i>
                        </a>
                    </li>
                  {% endif %}

              </ul>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
                {% if account.bio %}
                    {{ account.bio|linebreaksbr }}
                {% else %}
                    No bio
                {% endif %}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create_skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for skill in account.skill_set.all %}
                <tr>
              <td class="settings__tableInfo">
                <h4>{{ skill.name }}</h4>
                <p>
                  {{ skill.description|linebreaksbr }}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update_skill' skill_id=skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_skill' skill_id=skill.id %}"><i class="im im-x-mark-circle-o"></i>Delete</a>
              </td>
            </tr>
            {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create_project' %}">
                <i class="im im-plus"></i>
                Add Project
            </a>
          </div>

          <table class="settings__table">
             {% for project in account.project_set.all %}
             <tr>
               <td class="settings__thumbnail">
                 <a href="{% url 'detail_project' project_id=project.id %}">
                     <img src="{{ project.image.url }}" alt="{{ project.name}}" /></a>
               </td>
               <td class="settings__tableInfo">
                 <a href="{% url 'detail_project' project_id=project.id %}">{{ project.name }}</a>
                 <p>
                  {{ project.description|truncatechars:150|linebreaksbr }}
                </p>
               </td>
                <td class="settings__tableActions">
                 <a class="tag tag--pill tag--main settings__btn" href="{% url 'update_project' project_id=project.id %}"><i class="im im-edit"></i> Edit</a>
                 <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_project' project_id=project.id %}"><i class="im im-x-mark-circle-o"></i>
                   Delete</a>
                </td>
             </tr>
             {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

app_users/templates/app_users/inbox.html
{% extends 'base/base.html' %}

{% block content %}
<main class="inbox my-xl">
    <div class="content-box">
        <h3 class="inbox__title">New Messages (<span>{{ unread_messages|length }}</span>)</h3>

        <!-- O'qilmagan xabarlar -->
        <ul class="messages messages--unread">
            {% for message in unread_messages %}
                <li class="message">
                    <a href="{% url 'send_message' message.id %}">
                        <span class="message__author">{{ message.sender.fullname }}</span>
                        <span class="message__subject">{{ message.subject }}</span>
                        <span class="message__date">{{ message.created_at|date:"F j, Y, g:i A" }}</span>
                    </a>
                </li>
            {% empty %}
                <li>No unread messages.</li>
            {% endfor %}
        </ul>

        <!-- O'qilgan xabarlar -->
        <h4>Read Messages</h4>
        <ul class="messages messages--read">
            {% for message in read_messages %}
                <li class="message">
                    <a href="{% url 'send_message' message.id %}">
                        <span class="message__author">{{ message.sender.fullname }}</span>
                        <span class="message__subject">{{ message.subject }}</span>
                        <span class="message__date">{{ message.created_at|date:"F j, Y, g:i A" }}</span>
                    </a>
                </li>
            {% empty %}
                <li>No read messages.</li>
            {% endfor %}
        </ul>
    </div>
</main>
{% endblock content %}

app_users/templates/app_users/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="auth">
        <div class="card">
            <div class="auth__header text-center">
                <a href="{% url 'developers' %}">
                    <img src="{% static 'images/icon.svg' %}" alt="icon" />
                </a>
                <h3>Account Login</h3>
                <p>Hello Developer, Welcome Back!</p>
            </div>

            <form action="" class="form auth__form" method="post">
                {% csrf_token %}
                <div style="display: flex; justify-content: center; align-items: center; gap: 20px; width: 100%;">
                    <!-- Google -->
                    <div style="width: 50px; height: 50px; display: flex; align-items: center; justify-content: center;">
                        <a href="{% url 'social:begin' 'google-oauth2' %}" style="display: flex; align-items: center; justify-content: center; width: 100%; height: 100%;">
                            <img class="MMImage-Origin" src="https://i.pinimg.com/736x/e5/42/19/e542199ba63df1aa16735bc0fb630cc3.jpg" alt="Continue with Google" aria-hidden="true">
                        </a>
                    </div>

                    <!-- GitHub -->
                    <div style="width: 50px; height: 50px; display: flex; align-items: center; justify-content: center;">
                        <a href="{% url 'social:begin' 'github' %}" style="display: flex; align-items: center; justify-content: center; width: 100%; height: 100%;">
<img class="MMImage-Origin" src="//avatars.mds.yandex.net/i?id=1b77522cab90dc31df6f2486a11db599_l-5474261-images-thumbs&amp;n=13" alt="Picture background" aria-hidden="true">                          </a>
                    </div>

                    <!-- LinkedIn -->
                    <div style="width: 50px; height: 50px; display: flex; align-items: center; justify-content: center;">
                        <a href="{% url 'social:begin' 'linkedin' %}" style="display: flex; align-items: center; justify-content: center; width: 100%; height: 100%;">
                            <img class="MMImage-Origin" src="https://www.pngitem.com/pimgs/m/49-494452_transparent-linkedin-icon-png-robotic-process-automation-rpa.png" alt="Continue with LinkedIn" aria-hidden="true">
                        </a>
                    </div>
                </div>

                <p style="text-align: center">Google, GitHub, LinkedIn - click on the logo to continue!</p>
                <hr>

                <div class="form__field">
                    <label for="formInput#email">Email: </label>
                    <input
                        class="input input--text"
                        id="formInput#email"
                        type="email"
                        name="username"
                    />
                </div>

                <div class="form__field">
                    <label for="formInput#password">Password: </label>
                    <input
                        class="input input--password"
                        id="formInput#password"
                        type="password"
                        name="password"
                    />
                </div>
                <div class="auth__actions">
                    <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
                    <a href="{% url 'password_reset' %}">Forget Password?</a>
                </div>
            </form>

            <div class="auth__alternative">
                <p>Don’t have an Account?</p>
                <a href="{% url 'registration' %}">Sign Up</a>
            </div>
        </div>
    </div>
{% endblock content %}

app_users/templates/app_users/registration.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="{% url 'developers' %}">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a>
          <h3>Account SignUp</h3>
          <p>Create a new developer account</p>
        </div>

        <form action="#" class="form auth__form" method="post">
            {% csrf_token %}
        
          {% for field in form %}
          <div class="form__field">
            <label for="id_{{ field.name }}">{{ field.label }}: </label>
            {{ field }}
          </div>
          {% endfor %}
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Sign up" />
          </div>
        </form>
        <div class="auth__alternative">
          <p>Already have an Account?</p>
          <a href="{% url 'login' %}">Log In</a>
        </div>
      </div>
    </div>
{% endblock content %}